"""Constants for the Weishaupt WTC integration."""

DOMAIN = "weishaupt_wtc"

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_HK1_NAME = "hk1_name"
CONF_HK2_NAME = "hk2_name"
CONF_HK3_NAME = "hk3_name"

DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "Admin123"
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 30
MAX_SCAN_INTERVAL = 300
SCAN_INTERVAL_STEP = 10
DEFAULT_PORT = 80

DEFAULT_HK1_NAME = "Heizkreis 1"
DEFAULT_HK2_NAME = "Heizkreis 2"
DEFAULT_HK3_NAME = "Heizkreis 3"
DEFAULT_HEATING_CIRCUIT_NAMES = {
    1: DEFAULT_HK1_NAME,
    2: DEFAULT_HK2_NAME,
    3: DEFAULT_HK3_NAME,
}

API_ENDPOINT = "/ajax/CanApiJson.json"

# CanApiJson commands
CMD_GET = 0x01
CMD_RESPONSE = 0x02
CMD_SET = 0x03
CMD_ACK = 0x04
CMD_ERROR = 0x05
CMD_GET_STRING = 0x11
CMD_RESPONSE_STRING = 0x12
CMD_SET_STRING = 0x13
CMD_ACK_STRING = 0x14

# Source identifiers
SRC_DDC = "DDC"
SRC_SYS = "SYS"
